# -*- coding: utf-8 -*-
"""Final_Project_Python_DEDIEU_COUADAU_ITART.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JJPcJK-y5N4RYwjN2qcZmjpmHSa4HTv1

FINAL GROUP PROJECT: DEDIEU Lara - COUADAU Léa - ITART LONGUEVILLE Charlotte
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""This code will allow us to analyze the effect of the 2008 crisis on 23 major French companies. We have decided to select 3 firms within 6 different industries: Energy, Banking & Financial Services, Automotive, Luxury Goods, Consumer Goods & Distribution, Technology & Defense.

First analysis - The Income Statement
"""

file_name = ('/content/drive/MyDrive/Clean_data.xlsx')
df = pd.read_excel(file_name)
df

#Show the first three values
df.head(3)

df.columns

#Select the relevant columns
columns_to_select = ['Date','Company_name', 'Revenues_from_Business_Activties', 'Income_Available_to_Common_Shares']

df_simple = df[columns_to_select]

#Define the columns to select and their new names
column_rename_dict = {'Revenues_from_Business_Activties': 'Revenue', 
                      'Income_Available_to_Common_Shares': 'Net Income'}

df_simple = df_simple.rename(columns = column_rename_dict)

df_simple.describe()

df_simple.head(5)

#Select a specific data range
start_date = '31-12-2003'
end_date = '31-12-2013'

df_date = df_simple[(df_simple.Date >= start_date)&(df_simple.Date <= end_date)]

#Print the cleaned database with only the required columns and data range
df_date

#Net Income calculation
columns_to_select = ['Net Income','Company_name']

#Select the end date
df_end = df_date[df_date.Date==end_date]

df_end

#Select the start date
df_start = df_date[df_date.Date==start_date]

df_start

#Select only the Net Income
columns_to_take = ['Net Income', 'Company_name']
df_end = df_date[df_date.Date==end_date][columns_to_take].set_index('Company_name')
df_start = df_date[df_date.Date==start_date][columns_to_take].set_index('Company_name')

df_start

#Evolution calculation
df_evolution = (df_end - df_start) / df_start

color = ['g' if value > 0 else 'r' for value in df_evolution['Net Income']]
plt.figure(figsize=(10,10))
plt.bar(df_evolution.index, df_evolution['Net Income'], color=color)
plt.xticks(rotation=45, ha='right');

"""Interpretation: We can affirm that certain companies such as Véolia, Société Générale, Stellantis, Renault, Kering, Bonduelle, Carrefour and especially Capgemini, were deeply affected by the 2008 crisis as they register a negative evolution rate.

Second Analysis - Financial Ratios
"""

file_name = ('/content/drive/MyDrive/Python_Ratios .xlsx')
df = pd.read_excel(file_name)
df

#Group by industry
df.groupby(by='Industry').mean()

#Group by date
df.groupby(by='Date').mean()

df_table = df.groupby(by=['Date','Industry']).mean()

#Print the table displaying the mean of both ratios according to the industries and dates
df_table

"""A) Interpretation of the OPOA Ratio"""

#OPOA 2003
df_OPOA_2003 = df_table.loc['31-12-2003']['OPOA']

df_OPOA_2003

#Plot OPOA in 2003
plt.figure(figsize=(10,5))
df_OPOA_2003.plot()
my_plot = df_OPOA_2003.plot(title='OPOA 2003', color="blue")
plt.xticks(rotation=45, ha='right');

#Function to plot ratios according to the date
def plotdf(dataframe,title):
  plt.figure(figsize=(10,5))
  dataframe.plot()
  my_plot = dataframe.plot(title=title, color="blue")
  plt.xticks(rotation=45, ha='right');

#Function to plot ratios according to the date + custom color
def plotdf_color(dataframe,title, my_color):
  plt.figure(figsize=(10,10))
  dataframe.plot()
  my_plot = dataframe.plot(title=title, color=my_color)
  plt.xticks(rotation=45, ha='right');

#Function to display the maximum and minimum values
def min_max(dataframe):
  Maximum = dataframe.idxmax()
  Minimum = dataframe.idxmin()
  text = f'The maximum sector is: {Maximum} \nThe minimum sector is: {Minimum}'
  return text

#OPOA 2008
df_OPOA_2008 = df_table.loc['31-12-2008']['OPOA']

#OPOA 2008
plotdf_color(df_OPOA_2008,'OPOA 2008', my_color='green')

#OPOA 2013
df_OPOA_2013 = df_table.loc['31-12-2013']['OPOA']

#OPOA 2013
plotdf_color(df_OPOA_2008,'OPOA 2013', my_color='purple')

#Conclusion OPOA 2003
print(min_max(df_OPOA_2003))

#Conclusion OPOA 2008
print(min_max(df_OPOA_2008))

#Conclusion OPOA 2013
print(min_max(df_OPOA_2013))

"""B) Interpretation of the Book to Market Ratio"""

#Book to Market 2003
df_Book_to_Market_2003 = df_table.loc['31-12-2003']['Book to Market']
plotdf_color(df_Book_to_Market_2003,'Book to Market 2003', my_color='blue')

#Book to Market 2008
df_Book_to_Market_2008 = df_table.loc['31-12-2008']['Book to Market']
plotdf_color(df_Book_to_Market_2008,'Book to Market 2008', my_color='green')

#Book to Market 2013
df_Book_to_Market_2013 = df_table.loc['31-12-2013']['Book to Market']
plotdf_color(df_Book_to_Market_2013,'Book to Market 2013', my_color='purple')

#Conclusion Book to Market 2003
print(min_max(df_Book_to_Market_2003))

#Conclusion Book to Market 2008
print(min_max(df_Book_to_Market_2008))

#Conclusion Book to Market 2013
print(min_max(df_Book_to_Market_2013))

"""C) Comparison of both ratios

To conclude, we can affirm that the results obtained are logical with the effect of the Subprimes crisis. Indeed, as we can observe from the OPOA ratio, the sector which was the most profitable during (2008) and after the crisis (2013) was the luxury industry. On the opposite, companies within the banking sector were deeply hurt by the crisis as they registered the worst financial results. 

Adding to that, if we observe the Book to Market Ratio, the ending conclusion in 2013 shows the opposite. The banking sector due to its fragility was undervalued. In contrast, luxury firms registered the lowest Book to Market Ratios compared to the other industries. As they focus more on intangible assets such as brand recognition and customer loyalty, they often have high market values compared to their book values. 

Hence we can affirm that as expected, the banking industry was the most affected sector, while luxury companies were less impacted by the 2008 crisis.
"""